title: Modding Playground
description: >-
  Ninni and Andante, making mods
url: https://moddingplayground.net

theme: minima
plugins:
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:path/
