title: Modding Playground
url: https://moddingplayground.net

theme: minima
plugins:
  - jekyll-feed

projects-1:
  twigs:
projects-2:
  thematic:
  packed:
  macaws:
  endangered:
  sofishticated:

collections:
  pages:
    output: true
    permalink: /:path/
