title: Modding Playground
description: >-
  Ninni and Andante, making mods
url: https://moddingplayground.net

theme: minima
plugins:
  - jekyll-feed

projects:
  twigs:
  thematic:
  endangered:
  macaws:
  sofishticated:

collections:
  pages:
    output: true
    permalink: /:path/
